secrets:
  mysql_password:
    environment: DB_PASSWORD
volumes:
  nginx:
  static_files_cfchem:
  cert:
services:
  cfchem_api:
    build:
      context: ./app
    depends_on:
      mysql:
        condition: service_healthy
  cfchem_ui:
    build:
      context: https://github.com/Jonathan-Wahl/CFChemUI.git#TINX-35
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npx vite build
    volumes:
      - static_files_cfchem:/app/dist/
  nginx:
    image: nginx:1
    volumes:
      - static_files_cfchem:/usr/share/nginx/html/static_files_cfchem:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      cfchem_api:
        condition: service_started
      cfchem_ui:
        condition: service_completed_successfully
      # certbot:
      #   condition: service_completed_successfully
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=${DB_USER:-db_user}
      - MYSQL_PASSWORD=${DB_USER:-db_password}
      - MYSQL_DATABASE=${DB_USER:-db_database}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    secrets:
      - mysql_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
  # certbot:
  #   image: neilpang/acme.sh
  #   volumes:
  #     - cert:/out
  #   command: --issue -d example.com  --dns dns_cf

